version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  "c++20":
    docker:
      - image: johnmcfarlane/cnl_ci:gcc-9
    steps:
      - checkout
      - run:
          name: Run tests
          command: NUM_CPUS=2 . /root/project/.circleci/test.sh 20

  "c++17-arm7":
    docker:
      - image: johnmcfarlane/cnl_ci:gcc-9
    steps:
      - checkout
      - run:
          name: Run tests
          command: NUM_CPUS=2 . /root/project/.circleci/test-arm.sh
          no_output_timeout: 20m

  "c++17":
    docker:
      - image: johnmcfarlane/cnl_ci:gcc-9
    steps:
      - checkout
      - run:
          name: Run tests
          command: NUM_CPUS=2 . /root/project/.circleci/test.sh 17

  "c++14":
    docker:
      - image: johnmcfarlane/cnl_ci:gcc-9
    steps:
      - checkout
      - run:
          name: Run tests
          command: TEST_VC=OFF NUM_CPUS=2 . /root/project/.circleci/test.sh 14

  "c++11":
    docker:
      - image: johnmcfarlane/cnl_ci:gcc-9
    steps:
      - checkout
      - run:
          name: Run tests
          command: TEST_VC=OFF NUM_CPUS=2 . /root/project/.circleci/test.sh 11

workflows:
  version: 2
  build:
    jobs:
      - "c++20"
      - "c++17"
      - "c++14"
      - "c++11"
      - "c++17-arm7"
